// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbD8JOH4PXJvdnSPR3VY4sm4m9fc7aFSY',
    appId: '1:993853863782:web:f601f3771b67ffba757aa7',
    messagingSenderId: '993853863782',
    projectId: 'alerm-b6c51',
    authDomain: 'alerm-b6c51.firebaseapp.com',
    storageBucket: 'alerm-b6c51.firebasestorage.app',
    measurementId: 'G-DTKSLNHWJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFyXJE_frbdep28Dk7OnW3lvRVGJeYOtU',
    appId: '1:993853863782:android:6b7a582bb226821e757aa7',
    messagingSenderId: '993853863782',
    projectId: 'alerm-b6c51',
    storageBucket: 'alerm-b6c51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMyhY9RxQsF42s4aXVZcsesTFSig8IPA0',
    appId: '1:993853863782:ios:eb967808aedeafa1757aa7',
    messagingSenderId: '993853863782',
    projectId: 'alerm-b6c51',
    storageBucket: 'alerm-b6c51.firebasestorage.app',
    iosBundleId: 'com.example.alerm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMyhY9RxQsF42s4aXVZcsesTFSig8IPA0',
    appId: '1:993853863782:ios:eb967808aedeafa1757aa7',
    messagingSenderId: '993853863782',
    projectId: 'alerm-b6c51',
    storageBucket: 'alerm-b6c51.firebasestorage.app',
    iosBundleId: 'com.example.alerm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbD8JOH4PXJvdnSPR3VY4sm4m9fc7aFSY',
    appId: '1:993853863782:web:012ffec7b1442dca757aa7',
    messagingSenderId: '993853863782',
    projectId: 'alerm-b6c51',
    authDomain: 'alerm-b6c51.firebaseapp.com',
    storageBucket: 'alerm-b6c51.firebasestorage.app',
    measurementId: 'G-SH20BNZKCJ',
  );

}